# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import process_pb2 as process__pb2


class ProcssStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PreProcess = channel.unary_unary(
                '/process.Procss/PreProcess',
                request_serializer=process__pb2.PreProcessRequest.SerializeToString,
                response_deserializer=process__pb2.PreProcessResponse.FromString,
                )
        self.PostProcess = channel.unary_unary(
                '/process.Procss/PostProcess',
                request_serializer=process__pb2.PostProcessRequest.SerializeToString,
                response_deserializer=process__pb2.PostProcessResponse.FromString,
                )


class ProcssServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PreProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcssServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PreProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.PreProcess,
                    request_deserializer=process__pb2.PreProcessRequest.FromString,
                    response_serializer=process__pb2.PreProcessResponse.SerializeToString,
            ),
            'PostProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.PostProcess,
                    request_deserializer=process__pb2.PostProcessRequest.FromString,
                    response_serializer=process__pb2.PostProcessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'process.Procss', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Procss(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PreProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/process.Procss/PreProcess',
            process__pb2.PreProcessRequest.SerializeToString,
            process__pb2.PreProcessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/process.Procss/PostProcess',
            process__pb2.PostProcessRequest.SerializeToString,
            process__pb2.PostProcessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
