# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: process.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprocess.proto\x12\x07process\"\"\n\x11PreProcessRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"1\n\x12PreProcessResponse\x12\r\n\x05shape\x18\x01 \x03(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"1\n\x12PostProcessRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x04\"\"\n\x04Pred\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04prob\x18\x02 \x01(\x02\"3\n\x13PostProcessResponse\x12\x1c\n\x05preds\x18\x01 \x03(\x0b\x32\r.process.Pred2\x99\x01\n\x06Procss\x12\x45\n\nPreProcess\x12\x1a.process.PreProcessRequest\x1a\x1b.process.PreProcessResponse\x12H\n\x0bPostProcess\x12\x1b.process.PostProcessRequest\x1a\x1c.process.PostProcessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'process_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PREPROCESSREQUEST']._serialized_start=26
  _globals['_PREPROCESSREQUEST']._serialized_end=60
  _globals['_PREPROCESSRESPONSE']._serialized_start=62
  _globals['_PREPROCESSRESPONSE']._serialized_end=111
  _globals['_POSTPROCESSREQUEST']._serialized_start=113
  _globals['_POSTPROCESSREQUEST']._serialized_end=162
  _globals['_PRED']._serialized_start=164
  _globals['_PRED']._serialized_end=198
  _globals['_POSTPROCESSRESPONSE']._serialized_start=200
  _globals['_POSTPROCESSRESPONSE']._serialized_end=251
  _globals['_PROCSS']._serialized_start=254
  _globals['_PROCSS']._serialized_end=407
# @@protoc_insertion_point(module_scope)
